apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: core-backend-Mandar
  description: Sample service to get started
  annotations:
    backstage.io/techdocs-ref: dir:.
    backstage.io/kubernetes-id: pythonsvc
    backstage.io/kubernetes-namespace: sample
    backstage.io/kubernetes-namespace: prod
  tags:
    - sample
    - core
    - mandar
  links:
    - url: https://developer.harness.io/docs/category/get-started-with-idp
      title: Core Backend Endpoint
      icon: search
spec:
  type: service
  lifecycle: experimental
  owner: platformteam
  system: workshop
  dependsOn:
    - resource:default/core-db
  providesApis:
    - core-api-Mandar
